-- Starter widgets, so a fresh marketplace is not empty.
-- Owned by a curator page whose edit token is a fixed, public, non-secret value.

insert into public.pages (slug, edit_token, display_name, prefs, widgets)
values ('starters', '00000000-0000-4000-8000-000000000000', 'mymainpage', '{}'::jsonb, '[]'::jsonb)
on conflict (slug) do nothing;

insert into public.market_items (author_slug, author_name, title, description, icon, tags, spec)
values
  ('starters', 'mymainpage', 'To-do', 'Tasks with a done counter and progress bar.', '✅', '{productivity,lists}', '{"kind":"custom","id":"todo-a7j761","title":"To-do","icon":"✅","span":1,"state":{"draft":"","items":[]},"body":[{"t":"row","gap":2,"children":[{"t":"input","bind":"state.draft","placeholder":"Add a task…","grow":true,"onSubmit":[{"a":"push","path":"state.items","value":{"id":"{{uid()}}","text":"{{state.draft}}","done":false}},{"a":"set","path":"state.draft","value":""}]},{"t":"button","label":"Add","variant":"primary","on":[{"a":"push","path":"state.items","value":{"id":"{{uid()}}","text":"{{state.draft}}","done":false}},{"a":"set","path":"state.draft","value":""}]}]},{"t":"progress","value":"{{count(state.items,''done'')}}","max":"{{len(state.items)}}","label":"{{count(state.items,''done'')}} of {{len(state.items)}} done"},{"t":"repeat","each":"state.items","as":"item","empty":"Nothing here yet.","children":[{"t":"row","gap":2,"align":"between","children":[{"t":"checkbox","bind":"state.items[{{itemIndex}}].done"},{"t":"text","value":"{{item.text}}","grow":true,"strikeWhen":"item.done"},{"t":"button","label":"✕","variant":"ghost","on":{"a":"removeAt","path":"state.items","index":"{{itemIndex}}"}}]}]}]}'::jsonb),
  ('starters', 'mymainpage', 'Habit tracker', 'Seven-day grid, one row per habit, streak count per row.', '🔥', '{habits,health}', '{"kind":"custom","id":"habit-mhnm3r","title":"Habit tracker","icon":"🔥","span":2,"state":{"draft":"","days":["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],"habits":[{"id":"h1","text":"Read 20 min","marks":[false,false,false,false,false,false,false]},{"id":"h2","text":"Workout","marks":[false,false,false,false,false,false,false]}]},"body":[{"t":"row","gap":2,"children":[{"t":"input","bind":"state.draft","placeholder":"New habit…","grow":true,"onSubmit":[{"a":"push","path":"state.habits","value":{"id":"{{uid()}}","text":"{{state.draft}}","marks":[false,false,false,false,false,false,false]}},{"a":"set","path":"state.draft","value":""}]},{"t":"button","label":"Add","variant":"primary","on":[{"a":"push","path":"state.habits","value":{"id":"{{uid()}}","text":"{{state.draft}}","marks":[false,false,false,false,false,false,false]}},{"a":"set","path":"state.draft","value":""}]}]},{"t":"repeat","each":"state.habits","as":"habit","empty":"Add a habit to start a streak.","children":[{"t":"row","gap":2,"align":"between","children":[{"t":"text","value":"{{habit.text}}","grow":true},{"t":"row","gap":1,"children":[{"t":"repeat","each":"state.days","as":"day","children":[{"t":"button","label":"{{habit.marks[dayIndex] ? ''●'' : ''○''}}","variant":"ghost","on":{"a":"toggle","path":"state.habits[{{habitIndex}}].marks[{{dayIndex}}]"}}]}]},{"t":"badge","value":"{{count(habit.marks)}}/7","tone":"accent"},{"t":"button","label":"✕","variant":"ghost","on":{"a":"removeAt","path":"state.habits","index":"{{habitIndex}}"}}]}]},{"t":"divider"},{"t":"text","value":"{{join(state.days,''  '')}}","muted":true,"size":"xs"}]}'::jsonb),
  ('starters', 'mymainpage', 'Pomodoro', '25/5/15 focus timer that counts finished sessions.', '🍅', '{focus,time}', '{"kind":"custom","id":"pomodoro-tbyhj2","title":"Pomodoro","icon":"🍅","span":1,"state":{"left":1500,"running":false,"done":0},"body":[{"t":"timer","bind":"state.left","running":"state.running","onDone":[{"a":"set","path":"state.running","value":false},{"a":"inc","path":"state.done","by":1},{"a":"sound","name":"ding"}]},{"t":"row","gap":2,"children":[{"t":"button","label":"{{state.running ? ''Pause'' : ''Start''}}","variant":"primary","grow":true,"on":{"a":"toggle","path":"state.running"}},{"t":"button","label":"Reset","variant":"ghost","on":[{"a":"set","path":"state.left","value":1500},{"a":"set","path":"state.running","value":false}]}]},{"t":"row","gap":2,"children":[{"t":"button","label":"25m","variant":"ghost","grow":true,"on":{"a":"set","path":"state.left","value":1500}},{"t":"button","label":"5m","variant":"ghost","grow":true,"on":{"a":"set","path":"state.left","value":300}},{"t":"button","label":"15m","variant":"ghost","grow":true,"on":{"a":"set","path":"state.left","value":900}}]},{"t":"stat","label":"Sessions finished","value":"{{state.done}}"}]}'::jsonb),
  ('starters', 'mymainpage', 'Scratchpad', 'A plain scratchpad that remembers itself.', '📝', '{notes}', '{"kind":"custom","id":"notes-1lchof","title":"Scratchpad","icon":"📝","span":1,"state":{"text":""},"body":[{"t":"textarea","bind":"state.text","placeholder":"Think out loud…","rows":7},{"t":"text","value":"{{len(state.text)}} characters","muted":true,"size":"xs"}]}'::jsonb),
  ('starters', 'mymainpage', 'Water', 'Glasses per day against a goal.', '💧', '{health}', '{"kind":"custom","id":"water-x8m8kn","title":"Water","icon":"💧","span":1,"state":{"glasses":0,"goal":8},"body":[{"t":"stat","label":"Today","value":"{{state.glasses}} / {{state.goal}} glasses"},{"t":"progress","value":"{{state.glasses}}","max":"{{state.goal}}"},{"t":"row","gap":2,"children":[{"t":"button","label":"+1 glass","variant":"primary","grow":true,"on":{"a":"inc","path":"state.glasses","by":1}},{"t":"button","label":"−","variant":"ghost","on":{"a":"set","path":"state.glasses","value":"{{max(0, state.glasses - 1)}}"}},{"t":"button","label":"Reset","variant":"ghost","on":{"a":"set","path":"state.glasses","value":0}}]}]}'::jsonb),
  ('starters', 'mymainpage', 'Spending', 'Log spending against a monthly budget.', '💸', '{money}', '{"kind":"custom","id":"expenses-7n473x","title":"Spending","icon":"💸","span":1,"state":{"label":"","amount":"","items":[],"budget":500},"body":[{"t":"stat","label":"Spent this month","value":"{{fixed(sum(state.items,''amount''),2)}}","hint":"budget {{state.budget}}"},{"t":"progress","value":"{{sum(state.items,''amount'')}}","max":"{{state.budget}}"},{"t":"row","gap":2,"children":[{"t":"input","bind":"state.label","placeholder":"What for?","grow":true},{"t":"input","bind":"state.amount","placeholder":"0","inputType":"number"},{"t":"button","label":"Add","variant":"primary","on":[{"a":"push","path":"state.items","value":{"id":"{{uid()}}","text":"{{state.label}}","amount":"{{num(state.amount)}}","day":"{{today()}}"}},{"a":"set","path":"state.label","value":""},{"a":"set","path":"state.amount","value":""}]}]},{"t":"repeat","each":"state.items","as":"item","empty":"No spending logged.","children":[{"t":"row","align":"between","gap":2,"children":[{"t":"text","value":"{{item.text}}","grow":true},{"t":"text","value":"{{fixed(item.amount,2)}}","muted":true},{"t":"button","label":"✕","variant":"ghost","on":{"a":"removeAt","path":"state.items","index":"{{itemIndex}}"}}]}]}]}'::jsonb),
  ('starters', 'mymainpage', 'Reading list', 'Save links and articles, tick them off when read.', '📚', '{reading,lists}', '{"kind":"custom","id":"reading-7wzuyo","title":"Reading list","icon":"📚","span":1,"state":{"draft":"","items":[]},"body":[{"t":"row","gap":2,"children":[{"t":"input","bind":"state.draft","placeholder":"Title or link…","grow":true,"onSubmit":[{"a":"push","path":"state.items","value":{"id":"{{uid()}}","text":"{{state.draft}}","done":false}},{"a":"set","path":"state.draft","value":""}]},{"t":"button","label":"Save","variant":"primary","on":[{"a":"push","path":"state.items","value":{"id":"{{uid()}}","text":"{{state.draft}}","done":false}},{"a":"set","path":"state.draft","value":""}]}]},{"t":"repeat","each":"state.items","as":"item","empty":"Nothing saved yet.","children":[{"t":"row","gap":2,"align":"between","children":[{"t":"checkbox","bind":"state.items[{{itemIndex}}].done"},{"t":"text","value":"{{item.text}}","grow":true,"strikeWhen":"item.done"},{"t":"button","label":"✕","variant":"ghost","on":{"a":"removeAt","path":"state.items","index":"{{itemIndex}}"}}]}]},{"t":"text","value":"{{count(state.items,''done'')}} finished","muted":true,"size":"xs"}]}'::jsonb),
  ('starters', 'mymainpage', 'Mood log', 'One tap a day, with a running log.', '🌤️', '{journal,health}', '{"kind":"custom","id":"mood-0aucgi","title":"Mood log","icon":"🌤️","span":1,"state":{"entries":[]},"body":[{"t":"row","gap":2,"children":[{"t":"button","label":"😄","variant":"ghost","grow":true,"on":{"a":"push","path":"state.entries","value":{"id":"{{uid()}}","text":"😄","day":"{{today()}}"}}},{"t":"button","label":"🙂","variant":"ghost","grow":true,"on":{"a":"push","path":"state.entries","value":{"id":"{{uid()}}","text":"🙂","day":"{{today()}}"}}},{"t":"button","label":"😐","variant":"ghost","grow":true,"on":{"a":"push","path":"state.entries","value":{"id":"{{uid()}}","text":"😐","day":"{{today()}}"}}},{"t":"button","label":"😔","variant":"ghost","grow":true,"on":{"a":"push","path":"state.entries","value":{"id":"{{uid()}}","text":"😔","day":"{{today()}}"}}}]},{"t":"repeat","each":"state.entries","as":"entry","empty":"Tap a face to log how today feels.","children":[{"t":"row","align":"between","gap":2,"children":[{"t":"text","value":"{{entry.text}}  {{entry.day}}","grow":true},{"t":"button","label":"✕","variant":"ghost","on":{"a":"removeAt","path":"state.entries","index":"{{entryIndex}}"}}]}]}]}'::jsonb),
  ('starters', 'mymainpage', 'Countdown', 'Days until any date you pick.', '📆', '{time}', '{"kind":"custom","id":"countdown-vr7g12","title":"Countdown","icon":"📆","span":1,"state":{"label":"New Year","date":"2027-01-01"},"body":[{"t":"stat","label":"{{state.label}}","value":"{{daysBetween(state.date, today())}} days","hint":"{{state.date}}"},{"t":"input","bind":"state.label","placeholder":"What are you counting to?"},{"t":"input","bind":"state.date","inputType":"date"}]}'::jsonb)
on conflict (author_slug, title) do update
  set description = excluded.description,
      tags = excluded.tags,
      spec = excluded.spec;

